// Generated by scripts/fetch-guide-images.ts — per-guide cover photos.
// Guides without an entry fall back to the per-country image.
export const guideImageBySlug: Record<string, string> = {
  "chiang-mai-digital-nomad-guide-2026": "/images/chiangmai.jpg",
  "kuala-lumpur-expat-neighborhoods-2026": "/images/kualalumpur.jpg",
  "vietnam-da-nang-neighborhood-guide-2026": "/images/danang.jpg",
  "thailand-dtv-visa-dlya-frilanserov-2026": "/images/guides/thailand-dtv-visa-dlya-frilanserov-2026.jpg",
  "vietnam-remote-work-visa-2026": "/images/guides/vietnam-remote-work-visa-2026.jpg",
  "indonesia-bali-e33g-remote-worker-visa-2026": "/images/guides/indonesia-bali-e33g-remote-worker-visa-2026.jpg",
  "malaysia-de-rantau-nomad-pass-2026": "/images/guides/malaysia-de-rantau-nomad-pass-2026.jpg",
  "sri-lanka-expat-guide-2026": "/images/guides/sri-lanka-expat-guide-2026.jpg",
  "bali-neighborhoods-guide-2026": "/images/guides/bali-neighborhoods-guide-2026.jpg",
  "cambodia-phnom-penh-expat-guide-2026": "/images/guides/cambodia-phnom-penh-expat-guide-2026.jpg",
  "bali-cost-of-living-2026": "/images/guides/bali-cost-of-living-2026.jpg",
  "chiang-mai-cost-of-living-2026": "/images/guides/chiang-mai-cost-of-living-2026.jpg",
  "ho-chi-minh-city-expat-guide-2026": "/images/guides/ho-chi-minh-city-expat-guide-2026.jpg",
  "phuket-digital-nomad-guide-2026": "/images/guides/phuket-digital-nomad-guide-2026.jpg",
  "best-coworking-spaces-bali-2026": "/images/guides/best-coworking-spaces-bali-2026.jpg",
  "open-bank-account-thailand-foreigner-2026": "/images/guides/open-bank-account-thailand-foreigner-2026.jpg",
  "thailand-tax-for-expats-2026": "/images/guides/thailand-tax-for-expats-2026.jpg",
  "health-insurance-expats-southeast-asia-2026": "/images/guides/health-insurance-expats-southeast-asia-2026.jpg",
  "bali-vs-chiang-mai-vs-da-nang-2026": "/images/guides/bali-vs-chiang-mai-vs-da-nang-2026.jpg",
  "philippines-digital-nomad-guide-2026": "/images/guides/philippines-digital-nomad-guide-2026.jpg"
};
