import { revalidateTag } from "next/cache";
import { NextRequest, NextResponse } from "next/server";
import { isAdmin } from "@/lib/admin";
import { isDbConfigured } from "@/lib/db";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

const COMMUNITY_PROFILES = [
  {
    userId: "community-user-001",
    displayName: "Sophie Martin",
    bio: "Freelance photographer from Lyon. Shooting portraits and street life across SEA for 3 years. Currently based in Canggu, available for collab projects.",
    city: "Canggu",
    country: "France",
    languages: ["English", "French", "Indonesian (basic)"],
    interests: ["photography", "surf", "plant-based food"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@sophie_sea_shots",
    avatarUrl: "https://i.pravatar.cc/300?u=sophie.martin.sea",
  },
  {
    userId: "community-user-002",
    displayName: "Dmitry Sokolov",
    bio: "Backend engineer (Go/Postgres) working remotely for a Berlin SaaS company. Chiang Mai for 2 years — coffee shops, mountains, bearable traffic. Ask me about Nimman neighborhoods.",
    city: "Chiang Mai",
    country: "Russia",
    languages: ["Russian", "English"],
    interests: ["hiking", "specialty coffee", "open source"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@dmitry_cm",
    avatarUrl: "https://i.pravatar.cc/300?u=dmitry.sokolov.cm",
  },
  {
    userId: "community-user-003",
    displayName: "Emma Wilson",
    bio: "Arrived in Da Nang as an ESL teacher, stayed for the food and the beach. Now teaching yoga and doing occasional editing work. An Thuong is underrated.",
    city: "Da Nang",
    country: "United Kingdom",
    languages: ["English"],
    interests: ["yoga", "swimming", "Vietnamese cooking"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=emma.wilson.danang",
  },
  {
    userId: "community-user-004",
    displayName: "Carlos García",
    bio: "Marketing consultant from Barcelona. Running campaigns for European brands targeting SEA markets. Bangkok suits my work hours — 4h overlap with CET without waking up early.",
    city: "Bangkok",
    country: "Spain",
    languages: ["Spanish", "English", "Catalan"],
    interests: ["marketing", "muay thai", "street food tours"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@carlos_bkk",
    avatarUrl: "https://i.pravatar.cc/300?u=carlos.garcia.bkk",
  },
  {
    userId: "community-user-005",
    displayName: "Hana Novak",
    bio: "Graphic designer and illustrator from Prague. Ubud gave me the creative space I couldn't find in Europe. I design brand identities for small hospitality businesses.",
    city: "Ubud",
    country: "Czech Republic",
    languages: ["Czech", "English", "German"],
    interests: ["illustration", "ceramics", "rice field walks"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@hana_designs",
    avatarUrl: "https://i.pravatar.cc/300?u=hana.novak.ubud",
  },
  {
    userId: "community-user-006",
    displayName: "Jake Thompson",
    bio: "Kiting, dropshipping, Ko Samui sunsets. Left a corporate job in Austin 4 years ago, haven't looked back. Run a small e-com store doing 6 figures remote.",
    city: "Ko Samui",
    country: "United States",
    languages: ["English", "Thai (survival)"],
    interests: ["kitesurfing", "e-commerce", "diving"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@jake_samui",
    avatarUrl: "https://i.pravatar.cc/300?u=jake.thompson.samui",
  },
  {
    userId: "community-user-007",
    displayName: "Nora Schmidt",
    bio: "Product manager at a fintech startup (Series B, full remote). Munich → HCMC three years ago. Obsessed with Vietnamese coffee, finding good pizza is still a work in progress.",
    city: "Ho Chi Minh City",
    country: "Germany",
    languages: ["German", "English", "Vietnamese (basic)"],
    interests: ["product management", "cycling", "board games"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=nora.schmidt.hcmc",
  },
  {
    userId: "community-user-008",
    displayName: "Priya Sharma",
    bio: "Data analyst working remotely for a Singapore-based logistics startup. Penang is perfect — food, culture, 1h to KL when I need the city. Georgetown mornings are something else.",
    city: "Penang",
    country: "India",
    languages: ["English", "Hindi", "Tamil (basic)"],
    interests: ["data viz", "cycling", "street art"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@priya_penang",
    avatarUrl: "https://i.pravatar.cc/300?u=priya.sharma.penang",
  },
  {
    userId: "community-user-009",
    displayName: "Lucas Fontaine",
    bio: "Professional chef from Lyon turned food entrepreneur. Running pop-up dinners in Bangkok that blend French technique with Thai ingredients. Monthly events, limited seats.",
    city: "Bangkok",
    country: "France",
    languages: ["French", "English", "Thai (basic)"],
    interests: ["gastronomy", "fermentation", "night markets"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@lucas_bkk_kitchen",
    avatarUrl: "https://i.pravatar.cc/300?u=lucas.fontaine.bkk",
  },
  {
    userId: "community-user-010",
    displayName: "Olga Kovalenko",
    bio: "Travel blogger and photographer from Kyiv. In Phuket since 2022. Document the nomad lifestyle honestly — costs, visa issues, the bad days too. 120K on Instagram.",
    city: "Phuket",
    country: "Ukraine",
    languages: ["Ukrainian", "Russian", "English"],
    interests: ["travel writing", "photography", "sea kayaking"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@olga_phuket_life",
    avatarUrl: "https://i.pravatar.cc/300?u=olga.kovalenko.phuket",
  },
  {
    userId: "community-user-011",
    displayName: "Tobias Lindqvist",
    bio: "Software architect, remote contractor for Swedish tech firms. Canggu for 18 months. Working on distributed systems by day, learning to surf by evening. Very slowly.",
    city: "Canggu",
    country: "Sweden",
    languages: ["Swedish", "English"],
    interests: ["distributed systems", "surfing", "scooter mechanics"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=tobias.lindqvist.canggu",
  },
  {
    userId: "community-user-012",
    displayName: "Aisha Abdullah",
    bio: "UX researcher working with Southeast Asian fintech companies. Malaysian, KL-based. Passionate about making financial products accessible to unbanked populations across the region.",
    city: "Kuala Lumpur",
    country: "Malaysia",
    languages: ["Malay", "English", "Mandarin"],
    interests: ["UX research", "accessibility", "urban cycling"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@aisha_ux_kl",
    avatarUrl: "https://i.pravatar.cc/300?u=aisha.abdullah.kl",
  },
  {
    userId: "community-user-013",
    displayName: "Michael O'Brien",
    bio: "Content creator from Melbourne. YouTube channel on budget living in SEA, 80K subscribers. Chiang Mai is my base — cost of living makes the numbers work at any subscriber count.",
    city: "Chiang Mai",
    country: "Australia",
    languages: ["English", "Thai (basic)"],
    interests: ["filmmaking", "budget travel", "Thai boxing"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@michael_obrien_nomad",
    avatarUrl: "https://i.pravatar.cc/300?u=michael.obrien.cm",
  },
  {
    userId: "community-user-014",
    displayName: "Yuki Watanabe",
    bio: "Japanese-English technical translator and localization consultant. Based in HCMC for 4 years. Help Japanese companies expand into Vietnam and vice versa.",
    city: "Ho Chi Minh City",
    country: "Japan",
    languages: ["Japanese", "English", "Vietnamese"],
    interests: ["linguistics", "literature", "Vietnamese coffee"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=yuki.watanabe.hcmc",
  },
  {
    userId: "community-user-015",
    displayName: "Sven Bergmann",
    bio: "Coordinator at an education NGO in Phnom Penh. We run vocational training programs in rural Cambodia. 6 years in-country, still learning how much I don't know.",
    city: "Phnom Penh",
    country: "Germany",
    languages: ["German", "English", "Khmer (intermediate)"],
    interests: ["development work", "photography", "cycling"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@sven_pp",
    avatarUrl: "https://i.pravatar.cc/300?u=sven.bergmann.pp",
  },
  {
    userId: "community-user-016",
    displayName: "Ana Sousa",
    bio: "Jewelry designer from Lisbon. Make slow, handcrafted pieces using local stones and recycled silver. Sell globally online, live quietly in Bali. Good life balance.",
    city: "Ubud",
    country: "Portugal",
    languages: ["Portuguese", "English", "Spanish"],
    interests: ["jewelry making", "silversmithing", "plant medicine"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=ana.sousa.ubud",
  },
  {
    userId: "community-user-017",
    displayName: "Ryan Mitchell",
    bio: "Full-stack web developer from Toronto. React + Node. Working with 3 long-term clients, mostly US startups. Bangkok because of the food scene — 2 years and not repeated a restaurant.",
    city: "Bangkok",
    country: "Canada",
    languages: ["English", "French (basic)"],
    interests: ["web dev", "food exploration", "tennis"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@ryan_bkk_dev",
    avatarUrl: "https://i.pravatar.cc/300?u=ryan.mitchell.bkk",
  },
  {
    userId: "community-user-018",
    displayName: "Natalia Ivanova",
    bio: "200h certified vinyasa yoga teacher from Moscow. Teaching at a retreat center in Koh Phangan. The full moon parties are loud but the mornings here are genuinely magical.",
    city: "Koh Phangan",
    country: "Russia",
    languages: ["Russian", "English"],
    interests: ["yoga", "meditation", "raw food"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@natalia_yoga_koh",
    avatarUrl: "https://i.pravatar.cc/300?u=natalia.ivanova.koh",
  },
  {
    userId: "community-user-019",
    displayName: "Omar Khalil",
    bio: "CPA working remotely for clients in the Gulf and Europe. Pattaya suits the budget and the timezone. If you need help with cross-border accounting for expats, I might be useful.",
    city: "Pattaya",
    country: "Lebanon",
    languages: ["Arabic", "English", "French"],
    interests: ["accounting", "fishing", "chess"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@omar_cpa_sea",
    avatarUrl: "https://i.pravatar.cc/300?u=omar.khalil.pattaya",
  },
  {
    userId: "community-user-020",
    displayName: "Clara Dubois",
    bio: "Product designer at a European health-tech company. Full remote since 2021. Da Nang was a weekend trip that turned into two years. Beach at 7am, Figma by 9.",
    city: "Da Nang",
    country: "France",
    languages: ["French", "English"],
    interests: ["product design", "swimming", "solo travel"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=clara.dubois.danang",
  },
  {
    userId: "community-user-021",
    displayName: "Piotr Kowalski",
    bio: "Indie game developer from Warsaw. Built two mobile games while living in Chiang Mai. The cost structure here makes indie sustainable in a way it wouldn't be in Europe.",
    city: "Chiang Mai",
    country: "Poland",
    languages: ["Polish", "English"],
    interests: ["game dev", "3D modeling", "mountain biking"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@piotr_game_cm",
    avatarUrl: "https://i.pravatar.cc/300?u=piotr.kowalski.cm",
  },
  {
    userId: "community-user-022",
    displayName: "Isabella Russo",
    bio: "Fashion and lifestyle content creator from Milan. Bali for the content, but also genuinely for the lifestyle. Seminyak base, Ubud weekends. Not all Instagram, some of it's real.",
    city: "Seminyak",
    country: "Italy",
    languages: ["Italian", "English", "French"],
    interests: ["fashion", "aesthetics", "local crafts"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@bella_bali_style",
    avatarUrl: "https://i.pravatar.cc/300?u=isabella.russo.bali",
  },
  {
    userId: "community-user-023",
    displayName: "Ben Cohen",
    bio: "Serial entrepreneur, currently building a marketplace for vetted travel services in SEA. Bangkok is the startup hub people underestimate. Great talent pool, reasonable office costs.",
    city: "Bangkok",
    country: "Israel",
    languages: ["Hebrew", "English"],
    interests: ["startups", "product", "Muay Thai"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@ben_cohen_bkk",
    avatarUrl: "https://i.pravatar.cc/300?u=ben.cohen.bkk",
  },
  {
    userId: "community-user-024",
    displayName: "Lin Mei",
    bio: "Finance manager at a regional PE firm, Singapore PR. Grew up in Chengdu, studied in London, landed here 5 years ago. Singapore is expensive but the quality of life trade-off is real.",
    city: "Singapore",
    country: "China",
    languages: ["Mandarin", "English", "Cantonese"],
    interests: ["finance", "running", "dim sum research"],
    contactVisibility: "PRIVATE" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=lin.mei.singapore",
  },
  {
    userId: "community-user-025",
    displayName: "José Rodrigues",
    bio: "DJ and music producer from São Paulo. Playing across SEA for 3 years — Ko Samui, Bali, Bangkok, KL. Produce remotely, play live. Ko Samui is home base when not touring.",
    city: "Ko Samui",
    country: "Brazil",
    languages: ["Portuguese", "English", "Spanish"],
    interests: ["music production", "DJing", "diving"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@jose_dj_sea",
    avatarUrl: "https://i.pravatar.cc/300?u=jose.rodrigues.samui",
  },
  {
    userId: "community-user-026",
    displayName: "Elena Popescu",
    bio: "Therapist (CBT) from Bucharest offering sessions online to expats across SEA. Living in Phuket. Specializing in relocation adjustment, burnout, and relationships under digital nomad stress.",
    city: "Phuket",
    country: "Romania",
    languages: ["Romanian", "English", "French"],
    interests: ["psychology", "mindfulness", "ocean swimming"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@elena_therapy_sea",
    avatarUrl: "https://i.pravatar.cc/300?u=elena.popescu.phuket",
  },
  {
    userId: "community-user-027",
    displayName: "Samuel Eriksson",
    bio: "Growth marketer specializing in B2C subscription products. Remote for a Stockholm company. HCMC for the energy and pace — it matches how fast the work moves.",
    city: "Ho Chi Minh City",
    country: "Norway",
    languages: ["Norwegian", "English"],
    interests: ["growth marketing", "running", "coffee culture"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=samuel.eriksson.hcmc",
  },
  {
    userId: "community-user-028",
    displayName: "Tara O'Sullivan",
    bio: "Copywriter and brand strategist from Dublin. Working with SaaS companies on messaging and positioning. KL is underrated for nomads — food, infrastructure, and English is everywhere.",
    city: "Kuala Lumpur",
    country: "Ireland",
    languages: ["English", "Irish (basic)"],
    interests: ["writing", "brand strategy", "hiking"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@tara_copy_kl",
    avatarUrl: "https://i.pravatar.cc/300?u=tara.osullivan.kl",
  },
  {
    userId: "community-user-029",
    displayName: "Maximilian Kirsch",
    bio: "Architect and urban designer from Munich. Consulting on sustainable hospitality projects across SEA. Penang fascinates me — the colonial grid meets tropical vernacular. Best shophouses in the region.",
    city: "Penang",
    country: "Germany",
    languages: ["German", "English"],
    interests: ["architecture", "urban planning", "street photography"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=maximilian.kirsch.penang",
  },
  {
    userId: "community-user-030",
    displayName: "Ji-yeon Kim",
    bio: "Wellness coach and Pilates instructor from Seoul. Running an online membership for Korean expats in SEA. Also teaching in-person classes in Bangkok three times a week.",
    city: "Bangkok",
    country: "South Korea",
    languages: ["Korean", "English", "Thai (basic)"],
    interests: ["pilates", "wellness coaching", "Korean food abroad"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@jiyeon_wellness",
    avatarUrl: "https://i.pravatar.cc/300?u=jiyeon.kim.bkk",
  },
  {
    userId: "community-user-031",
    displayName: "Marco van der Berg",
    bio: "Blockchain developer and smart contract auditor. Remote from Amsterdam, living in Canggu. Crypto community here is real — not just tourists. Good coworking options within scooter distance.",
    city: "Canggu",
    country: "Netherlands",
    languages: ["Dutch", "English"],
    interests: ["blockchain", "cryptography", "surfing"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@marco_blockchain_bali",
    avatarUrl: "https://i.pravatar.cc/300?u=marco.vandenberg.canggu",
  },
  {
    userId: "community-user-032",
    displayName: "Lara Okonkwo",
    bio: "International trade consultant from Lagos. Based in HCMC helping Nigerian and West African businesses navigate Vietnam and Cambodia sourcing. The manufacturing connections here are genuinely valuable.",
    city: "Ho Chi Minh City",
    country: "Nigeria",
    languages: ["English", "Yoruba", "French"],
    interests: ["trade", "import/export", "street photography"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@lara_trade_hcmc",
    avatarUrl: "https://i.pravatar.cc/300?u=lara.okonkwo.hcmc",
  },
  {
    userId: "community-user-033",
    displayName: "Felix Huber",
    bio: "Independent financial advisor for expats from Zurich. Specialize in cross-border tax planning, pension portability and investment for people who live between countries. Chiang Mai for 5 years.",
    city: "Chiang Mai",
    country: "Switzerland",
    languages: ["German", "French", "English"],
    interests: ["finance", "hiking", "specialty coffee"],
    contactVisibility: "PUBLIC" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@felix_expat_finance",
    avatarUrl: "https://i.pravatar.cc/300?u=felix.huber.cm",
  },
  {
    userId: "community-user-034",
    displayName: "Amelia Fraser",
    bio: "Primary school teacher from Brisbane, now teaching at an international school in Da Nang. The beach after school every day was the pitch I couldn't argue with. Two years in and no regrets.",
    city: "Da Nang",
    country: "Australia",
    languages: ["English"],
    interests: ["education", "beach volleyball", "cooking"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: false,
    avatarUrl: "https://i.pravatar.cc/300?u=amelia.fraser.danang",
  },
  {
    userId: "community-user-035",
    displayName: "Viktor Petrov",
    bio: "E-commerce entrepreneur from Moscow. Run a brand that sells outdoor gear across EU and North America, entirely managed from Bangkok. Logistics from here is easier than people think.",
    city: "Bangkok",
    country: "Russia",
    languages: ["Russian", "English"],
    interests: ["e-commerce", "supply chain", "Muay Thai"],
    contactVisibility: "MEMBERS" as const,
    showEmail: false, showPhone: false, showTelegram: true,
    telegram: "@viktor_ecom_bkk",
    avatarUrl: "https://i.pravatar.cc/300?u=viktor.petrov.bkk",
  },
];

export async function POST(req: NextRequest) {
  if (!isDbConfigured()) {
    return NextResponse.json({ error: "DB not configured" }, { status: 503 });
  }

  const admin = await isAdmin();
  if (!admin) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const result = await prisma.profile.createMany({
      data: COMMUNITY_PROFILES,
      skipDuplicates: true,
    });

    revalidateTag("community-profiles");
    revalidateTag("home-people");

    return NextResponse.json({
      ok: true,
      created: result.count,
      total: COMMUNITY_PROFILES.length,
      message: `Created ${result.count} new profiles (${COMMUNITY_PROFILES.length - result.count} already existed). Cache cleared.`,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
