// Fetch one topical Unsplash photo per guide into public/images/guides/<slug>.jpg
// and emit src/lib/guide-image-map.ts. Skips slugs that already have a file.
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

function curlJson(url: string): unknown {
  const out = execSync(`curl -s ${JSON.stringify(url)}`, { maxBuffer: 64 * 1024 * 1024 });
  return JSON.parse(out.toString());
}

function curlDownload(url: string, file: string): void {
  execSync(`curl -s -L -o ${JSON.stringify(file)} ${JSON.stringify(url)}`);
}

const queries: Record<string, string> = {
  "thailand-dtv-visa-dlya-frilanserov-2026": "bangkok grand palace thailand",
  "vietnam-remote-work-visa-2026": "ha long bay vietnam",
  "indonesia-bali-e33g-remote-worker-visa-2026": "bali temple gates handara",
  "malaysia-de-rantau-nomad-pass-2026": "petronas towers kuala lumpur night",
  "sri-lanka-expat-guide-2026": "sri lanka train tea plantation",
  "bali-neighborhoods-guide-2026": "canggu bali beach surf",
  "cambodia-phnom-penh-expat-guide-2026": "phnom penh royal palace cambodia",
  "bali-cost-of-living-2026": "bali rice terrace tegallalang",
  "chiang-mai-cost-of-living-2026": "thailand street food night market",
  "ho-chi-minh-city-expat-guide-2026": "ho chi minh city skyline",
  "phuket-digital-nomad-guide-2026": "phuket thailand beach aerial",
  "best-coworking-spaces-bali-2026": "coworking space laptop tropical",
  "open-bank-account-thailand-foreigner-2026": "bangkok skytrain city",
  "thailand-tax-for-expats-2026": "finance documents calculator desk",
  "health-insurance-expats-southeast-asia-2026": "doctor stethoscope health",
  "bali-vs-chiang-mai-vs-da-nang-2026": "traveler backpack looking map asia",
  "philippines-digital-nomad-guide-2026": "el nido palawan philippines",
};

type Result = {
  width: number; height: number; likes: number;
  urls: { raw: string };
  premium?: boolean;
};

async function pick(query: string): Promise<string | null> {
  const data = curlJson(
    `https://unsplash.com/napi/search/photos?query=${encodeURIComponent(query)}&per_page=10&orientation=landscape`,
  ) as { results: (Result & { urls: { raw: string } })[] };
  if (!data.results) return null;
  const ok = data.results.filter(
    (r) => r.urls.raw.includes("images.unsplash.com") && r.width >= 1600 && r.width > r.height,
  );
  ok.sort((a, b) => b.likes - a.likes);
  const best = ok[0];
  if (!best) return null;
  return best.urls.raw.split("?")[0] + "?w=1600&q=80&fm=jpg&fit=crop";
}

async function main() {
  const map: Record<string, string> = {};
  for (const [slug, query] of Object.entries(queries)) {
    const file = path.join("public/images/guides", `${slug}.jpg`);
    if (!fs.existsSync(file)) {
      const url = await pick(query);
      if (!url) { console.log("MISS", slug); continue; }
      curlDownload(url, file);
      if (!fs.existsSync(file) || fs.statSync(file).size < 20_000) {
        console.log("DL FAIL", slug);
        if (fs.existsSync(file)) fs.unlinkSync(file);
        continue;
      }
      console.log("OK  ", slug, `(${(fs.statSync(file).size / 1024).toFixed(0)} KB)`);
      await new Promise((r) => setTimeout(r, 800));
    } else {
      console.log("SKIP", slug, "(exists)");
    }
    map[slug] = `/images/guides/${slug}.jpg`;
  }

  const ts =
    "// Generated by scripts/fetch-guide-images.ts — per-guide cover photos.\n" +
    "// Guides without an entry fall back to the per-country image.\n" +
    "export const guideImageBySlug: Record<string, string> = " +
    JSON.stringify(map, null, 2) +
    ";\n";
  fs.writeFileSync("src/lib/guide-image-map.ts", ts);
  console.log("map written:", Object.keys(map).length, "entries");
}

main();
